HOST: http://www.google.com/

--- LL Sync API ---

---
Below are the details of the Lets Lynk Sync API. This API provides methods to sync the mobile database contents with the main server database.
---

--
User > ActivitySync

This method is for syncing activities to the mobile device.
--

Retrieve a collection of user activities

__Authentication:__ Required

__Authorization:__ The caller must be authorized as the owner of the user resource 

__URI Filters__: 

* modified (Integer) *the UTC unix time modified date*
* limit (Integer) *the maximum number of items to return*

     Example: `/users/1/activity_sync?modified=1380621400&limit=10`
GET /users/{user_id}/activity_sync{?limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
{
    "activities": [
        {
            "_activity_id": 1,
            "type": "connection",
            "date": 1380621600,
            "event_id": 1,
            "_modified": 1380621600
        },
        {
            "_activity_id": 2,
            "type": "goodie",
            "date": 1380610110,
            "event_id": 1,
            "_modified": 1380621720
        }
    ],
    "_modified": 1380621720,
    "_links": {
        "self": { "href": "/users/1/activity_sync?modified=1380621400&limit=10" },
        "next": { "href": "/users/1/activity_sync?modified=1380621720&limit=10" }
    }
}
+++++
< 404
< Content-Type: application/json
{
    "error": "The requested resource could not be found"
}


--
User > ConnectionsSync
This method is for syncing connections to the mobile device.
--

Retrieve a list of connections

__Authentication:__ Required

__Authorization:__ The caller must be authorized as the owner of the user resource 

__URI Filters__: 

* modified (Integer) *the UTC unix time modified date*
* limit (Integer) *the maximum number of items to return*

    Example `/users/1/connections_sync?modified=1380621400&limit=10`
GET /users/{user_id}/connections_sync{?limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
{
    "connections": [
        {
            "_connection_id": 1,
            "activity_id": 1,
            "contact_id": 10,
            "_modified": 1380621600
        },
        {
            "_connection_id": 2,
            "activity_id": 2,
            "contact_id": 11,
            "_modified": 1380621720
        }
    ],
    "_modified": 1380621720,
    "_links": {
        "self": { "href": "/users/1/connections_sync?modified=1380621400&limit=10" },
        "next": { "href": "/users/1/connections_sync?modified=1380621720&limit=10" }
    }
}
+++++
< 404
< Content-Type: application/json
{
    "error": "The requested resource could not be found"
}


--
User > ContactsSync
This method is for syncing contacts to the mobile device
--

Retreive a list of contacts

__Authentication:__ Required

__Authorization:__ The caller must be authorized as the owner of the user resource 

__URI Filters__: 

* modified (Integer) *the UTC unix time modified date*
* limit (Integer) *the maximum number of items to return*

    Example `/users/1/contacts_sync?modified=1380621400&limit=10`
GET /users/{user_id}/contacts_sync{?limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
{
    "contacts":[
        {
            "_contact_id": 10,
            "email" : "stevensegal@kickass.com",
            "title" : "Mr",
            "first_name" : "Steven",
            "last_name" : "Segal",
            "home_telephone" : "04444 123 456",
            "mobile_telephone" : "05555 123 456",
            "work_telephone" : "06666 123 456",
            "linked_in" : "http://linked.in/steven_segal",
            "facebook" : "http://facebook.com/stevan_segal",
            "twitter" : "@steven_segal",
            "google" : "+steven_segal",
            "company" : "Kick Ass Ltd",
            "job_title" : "Ass Kicker",
            "address_line_1" : "Address 1",
            "address_line_2" : "Address 2",
            "address_line_3" : "Address 3",
            "address_line_4" : "Address 4",
            "locality" : "NY",
            "region" : "NY",
            "postcode" : "K1KA55",
            "country" : "USA",
            "_qr_code": "12434-12414-asdsa1-123123",
            "avatar": {
                "_links" : {
                    "original": { "href": "https://i.letslynk.com/u/9fkoWokA/a/orig.jpg" },
                    "38": { "href": "https://i.letslynk.com/u/9fkoWokA/a/38.jpg" },
                    "50": { "href": "https://i.letslynk.com/u/9fkoWokA/a/50.jpg" },
                    "75": { "href": "https://i.letslynk.com/u/9fkoWokA/a/75.jpg" },
                    "100": { "href": "https://i.letslynk.com/u/9fkoWokA/a/100.jpg" },
                    "150": { "href": "https://i.letslynk.com/u/9fkoWokA/a/150.jpg" },
                    "200": { "href": "https://i.letslynk.com/u/9fkoWokA/a/200.jpg" },
                    "300": { "href": "https://i.letslynk.com/u/9fkoWokA/a/300.jpg" }
                    }
            },
            "banner": {
                "_links" : {
                    "original": { "href": "https://i.letslynk.com/u/9fkoWokA/b/orig.jpg" },
                    "320": { "href": "https://i.letslynk.com/u/9fkoWokA/b/320.jpg" },
                    "480": { "href": "https://i.letslynk.com/u/9fkoWokA/b/480.jpg" },
                    "612": { "href": "https://i.letslynk.com/u/9fkoWokA/b/612.jpg" },
                    "640": { "href": "https://i.letslynk.com/u/9fkoWokA/b/640.jpg" },
                    "720": { "href": "https://i.letslynk.com/u/9fkoWokA/b/720.jpg" },
                    "960": { "href": "https://i.letslynk.com/u/9fkoWokA/b/960.jpg" },
                    "1080": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1080.jpg" },
                    "1200": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1200.jpg" },
                    "1600": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1600.jpg" }
                }
            },
            "_deleted": false,
            "_modified": 1380621600
        },
        {
            "_contact_id": 11,
            "email" : "brucelee@kickass.com",
            "title" : "Mr",
            "first_name" : "Bruce",
            "last_name" : "Lee",
            "home_telephone" : "04444 123 457",
            "mobile_telephone" : "05555 123 457",
            "work_telephone" : "06666 123 457",
            "linked_in" : "http://linked.in/bruce_lee",
            "facebook" : "http://facebook.com/bruce_lee",
            "twitter" : "@bruce_lee",
            "google" : "+bruce_lee",
            "company" : "Kick Ass Ltd",
            "job_title" : "Ass Kicker",
            "address_line_1" : "Address 1",
            "address_line_2" : "Address 2",
            "address_line_3" : "Address 3",
            "address_line_4" : "Address 4",
            "locality" : "NY",
            "region" : "NY",
            "postcode" : "K1KA55",
            "country" : "USA",
            "_qr_code": "12434-12414-asdsa1-123124",
            "avatar": {
                "_links" : {
                    "original": { "href": "https://i.letslynk.com/u/9fkoWokA/a/orig.jpg" },
                    "38": { "href": "https://i.letslynk.com/u/9fkoWokA/a/38.jpg" },
                    "50": { "href": "https://i.letslynk.com/u/9fkoWokA/a/50.jpg" },
                    "75": { "href": "https://i.letslynk.com/u/9fkoWokA/a/75.jpg" },
                    "100": { "href": "https://i.letslynk.com/u/9fkoWokA/a/100.jpg" },
                    "150": { "href": "https://i.letslynk.com/u/9fkoWokA/a/150.jpg" },
                    "200": { "href": "https://i.letslynk.com/u/9fkoWokA/a/200.jpg" },
                    "300": { "href": "https://i.letslynk.com/u/9fkoWokA/a/300.jpg" }
                    }
            },
            "banner": {
                "_links" : {
                    "original": { "href": "https://i.letslynk.com/u/9fkoWokA/b/orig.jpg" },
                    "320": { "href": "https://i.letslynk.com/u/9fkoWokA/b/320.jpg" },
                    "480": { "href": "https://i.letslynk.com/u/9fkoWokA/b/480.jpg" },
                    "612": { "href": "https://i.letslynk.com/u/9fkoWokA/b/612.jpg" },
                    "640": { "href": "https://i.letslynk.com/u/9fkoWokA/b/640.jpg" },
                    "720": { "href": "https://i.letslynk.com/u/9fkoWokA/b/720.jpg" },
                    "960": { "href": "https://i.letslynk.com/u/9fkoWokA/b/960.jpg" },
                    "1080": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1080.jpg" },
                    "1200": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1200.jpg" },
                    "1600": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1600.jpg" }
                }
            },
            "_deleted": false,
            "_modified": 1380621720
        }
    ],
    "_modified": 1380621720,
    "_links": {
        "self": { "href": "/users/1/connections_sync?modified=1380621400&limit=10" },
        "next": { "href": "/users/1/connections_sync?modified=1380621720&limit=10" }
    }
}

--
User > EventsSync
A collection of events that the user is related to because:

1. They are a staff member,
2. They are a member of a team at that event
3. They are registered for the event
4. They have been invited to attend the event
--
A collection of events that the user is related to. This method is used to sync the mobile database.

__Authentication:__ Required

__Authorization:__ The caller must be authorized as the owner of the user resource 

__URI filters:__

* modified (Integer) *the modified date as a UTC unix timestamp. The method will return all events modified after this date.* 
* start (Integer) *the item number to start from. If not specified this will be set to 0 by default.*
* limit (Integer) *the maximum number of items to return. If not specified this will be set to 10 by default.*


Example: `/users/1/events?modified=1380618000&start=0&limit=10`
GET /users/{user_id}/events_sync{?start,limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
< Content-Type: application/json
{
    "events": [
        {
            "_event_id": 1,
            "registered": true,
            "event_name" : "Ninja Anonymous Event",
            "description" : "Brief description about the event",
            "venue_name" : "ExCeL",
            "address_line_1" : "Address 1",
            "address_line_2" : "Address 2",
            "address_line_3" : "Address 3",
            "address_line_4" : "Address 4",
            "locality" : "London",
            "region" : "London",
            "postcode" : "",
            "country" : "UK",
            "timezone": "Europe/London",
            "days": [
                {
                    "_event_day_id": 1,
                    "opening_time": "2013-10-15T09:00:00Z",
                    "closing_time": "2013-10-15T17:00:00Z"   
                },
                {
                    "_event_day_id": 2,
                    "opening_time": "2013-10-16T09:00:00Z",
                    "closing_time": "2013-10-16T17:00:00Z"   
                }
            ],
            "profile_fields": {
                "first_name": true,
                "last_name": true,
                "work_telephone": false,
                "title": true,
                "country": false,
                "twitter": false,
                "locality": false,
                "linked_in": false,
                "mobile_telephone": false,
                "company": true,
                "home_telephone": false,
                "google": false,
                "facebook": false,
                "postcode": false,
                "region": false,
                "address_line_4": false,
                "job_title": true,
                "address_line_2": false,
                "address_line_3": false,
                "address_line_1": false
            },
            "questions": [
                {
                    "_question_id": 1,
                    "question_type": "radio",
                    "question_text": "What is your favourite martial art?",
                    "required": true,
                    "answers": [
                        {
                            "_answer_id": 1,
                            "answer_text": "Kung Fu"
                        },
                        {
                            "_answer_id": 2,
                            "answer_text": "Karate"
                        },
                        {
                            "_answer_id": 3,
                            "answer_text": "Kick Boxing"
                        }
                    ]
                },
                {
                    "_question_id": 2,
                    "question_type_id": "select",
                    "question_text": "Age group",
                    "required": false,
                    "answers": [
                        {
                            "_answer_id": 4,
                            "answer_text": "18-25"
                        },
                        {
                            "_answer_id": 5,
                            "answer_text": "26-34"
                        },
                        {
                            "_answer_id": 6,
                            "answer_text": "34+"
                        }
                    ]
                } 
            ],
            "_qr_code": "43ef7869-acba-4985-a932-5b5ad9f994ec",
            "avatar": {
                "_links" : {
                    "original": { "href": "https://i.letslynk.com/u/9fkoWokA/a/orig.jpg" },
                    "38": { "href": "https://i.letslynk.com/u/9fkoWokA/a/38.jpg" },
                    "50": { "href": "https://i.letslynk.com/u/9fkoWokA/a/50.jpg" },
                    "75": { "href": "https://i.letslynk.com/u/9fkoWokA/a/75.jpg" },
                    "100": { "href": "https://i.letslynk.com/u/9fkoWokA/a/100.jpg" },
                    "150": { "href": "https://i.letslynk.com/u/9fkoWokA/a/150.jpg" },
                    "200": { "href": "https://i.letslynk.com/u/9fkoWokA/a/200.jpg" },
                    "300": { "href": "https://i.letslynk.com/u/9fkoWokA/a/300.jpg" }
                    }
            },
            "banner": {
                "_links" : {
                    "original": { "href": "https://i.letslynk.com/u/9fkoWokA/b/orig.jpg" },
                    "320": { "href": "https://i.letslynk.com/u/9fkoWokA/b/320.jpg" },
                    "480": { "href": "https://i.letslynk.com/u/9fkoWokA/b/480.jpg" },
                    "612": { "href": "https://i.letslynk.com/u/9fkoWokA/b/612.jpg" },
                    "640": { "href": "https://i.letslynk.com/u/9fkoWokA/b/640.jpg" },
                    "720": { "href": "https://i.letslynk.com/u/9fkoWokA/b/720.jpg" },
                    "960": { "href": "https://i.letslynk.com/u/9fkoWokA/b/960.jpg" },
                    "1080": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1080.jpg" },
                    "1200": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1200.jpg" },
                    "1600": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1600.jpg" }
                }
            },
            "_deleted": false,
            "_modified": 1380621600
        }
    ],
    "_links": {
        "self": { "href": "/users/1/events_sync?modified=1380618000&limit=10" },
        "next": { "href": "/users/1/events_sync?modified=1383296400&start=10&limit=10" }
    },
    "_modified": 1383296400
}
+++++
< 404
< Content-Type: application/json
{
    "error": "The requested resource could not be found"
}


--
User > TagsSync
This method is for syncing tags to the mobile device.
--

Retrieve a list of tags

__Authentication:__ Required

__Authorization:__ The caller must be authorized as the owner of the user resource 

__URI Filters__: 

* modified (Integer) *the UTC unix time modified date*
* limit (Integer) *the maximum number of items to return*

    Example `/users/1/tags_sync?modified=1380621400&limit=10`
GET /users/{user_id}/tags_sync{?limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
{
    "tags": [
        {
            "_tag_id": 1,
            "name": "Hot Lead",
            "colour": "F7686B",
            "icon": "flame",
            "_deleted": false,
            "_modified": 1380621600
        },
        {
            "_tag_id": 2,
            "name": "Call back",
            "colour": "47B569",
            "icon": "phone",
            "_deleted": false,
            "_modified": 1380621720
        }
    ],
    "_modified": 1380621720,
    "_links": {
        "self": { "href": "/users/1/tags_sync?modified=1380621400&limit=10" },
        "next": { "href": "/users/1/tags_sync?modified=1380621720&limit=10" }
    }
}
+++++
< 404
< Content-Type: application/json
{
    "error": "The requested resource could not be found"
}


--
User > TagsAssignmentsSync
This method is for syncing tag assignments to the mobile device.
--

Retrieve a list of tag assignments

__Authentication:__ Required

__Authorization:__ The caller must be authorized as the owner of the user resource 

__URI Filters__: 

* modified (Integer) *the UTC unix time modified date*
* limit (Integer) *the maximum number of items to return*

    Example `/users/1/tags_sync?modified=1380621400&limit=10`
GET /users/{user_id}/tag_assignments_sync{?limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
{
    "tags_assignments": [
        {
            "_tag_assignment_id": 1,
            "tag_id": 1,
            "contact_id": 10,
            "_deleted": false,
            "_modified": 1380621600
        },
        {
            "_tag_assignment_id": 2,
            "tag_id": 2,
            "contact_id": 10,
            "_deleted": false,
            "_modified": 1380621720
        }
    ],
    "_modified": 1380621720,
    "_links": {
        "self": { "href": "/users/1/tag_assignments_sync?modified=1380621400&limit=10" },
        "next": { "href": "/users/1/tag_assignments_sync?modified=1380621720&limit=10" }
    }
}
+++++
< 404
< Content-Type: application/json
{
    "error": "The requested resource could not be found"
}


--
User > NotesSync
This method is for syncing notes to the mobile device.
--

Retrieve a list of notes

__Authentication:__ Required

__Authorization:__ The caller must be authorized as the owner of the user resource 

__URI Filters__: 

* modified (Integer) *the UTC unix time modified date*
* limit (Integer) *the maximum number of items to return*

    Example `/users/1/tags_sync?modified=1380621400&limit=10`
GET /users/{user_id}/notes_sync{?limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
{
    "notes": [
        {
            "_note_id": 1,
            "contact_id": 10,
            "note": "This is the note text. Blah blah",
            "date": 1380621600, 
            "_deleted": false,
            "_modified": 1380621600
        },
        {
            "_note_id": 2,
            "contact_id": 10,
            "note": "This is another note. Blah blah",
            "date": 1380621700, 
            "_deleted": false,
            "_modified": 1380621720
        }
    ],
    "_modified": 1380621720,
    "_links": {
        "self": { "href": "/users/1/notes_sync?modified=1380621400&limit=10" },
        "next": { "href": "/users/1/notes_sync?modified=1380621720&limit=10" }
    }
}
+++++
< 404
< Content-Type: application/json
{
    "error": "The requested resource could not be found"
}


--
User > GoodiesSync
This method is for syncing goodies to the mobile device.
--

Retrieve a list of notes

__Authentication:__ Required

__Authorization:__ The caller must be authorized as the owner of the user resource 

__URI Filters__: 

* modified (Integer) *the UTC unix time modified date*
* limit (Integer) *the maximum number of items to return*

    Example `/users/1/goodies_sync?modified=1380621400&limit=10`
GET /users/{user_id}/goodies_sync{?limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
{
    "goodies": [
        {
            "_goodie_id": 1,
            "activity_id": 9,
            "collected_date": 1380621600,
            "name": "2013 Product Brochure",
            "type": "Document",
            "sub_type": "pdf",
            "url": "/docs/team/1/asdpoqwefpj.pdf",
            "team_name": "Kung Fu Masters",
            "_deleted": false,
            "_modified": 1380621600
        },
        {
            "_goodie_id": 2,
            "activity_id": 10,
            "collected_date": 1380621712,
            "name": "2013 Fact File",
            "type": "video",
            "url": "/docs/team/1/asasfafgwwec.pdf",
            "thumbnail": {
				"_links": {
					"original": { "href": "https://i.letslynk.com/u/9fkoWokA/b/orig.jpg" },
					"320": { "href": "https://i.letslynk.com/u/9fkoWokA/b/320.jpg" },
					"480": { "href": "https://i.letslynk.com/u/9fkoWokA/b/480.jpg" },
					"612": { "href": "https://i.letslynk.com/u/9fkoWokA/b/612.jpg" },
					"640": { "href": "https://i.letslynk.com/u/9fkoWokA/b/640.jpg" },
					"720": { "href": "https://i.letslynk.com/u/9fkoWokA/b/720.jpg" },
					"960": { "href": "https://i.letslynk.com/u/9fkoWokA/b/960.jpg" },
					"1080": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1080.jpg" },
					"1200": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1200.jpg" },
					"1600": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1600.jpg" }
				}
			},
            "team_name": "Kung Fu Masters", 
            "_deleted": false,
            "_modified": 1380621712
        },
        {
            "_goodie_id": 3,
            "activity_id": 11,
            "collected_date": 1380621720,
            "name": "2013 Picture",
            "type": "image",
            "url": "https://www.youtube.com/watch?v=XJDUgkSzh-Y",
            "thumbnail": {
				"_links": {
					"original": { "href": "https://i.letslynk.com/u/9fkoWokA/b/orig.jpg" },
					"320": { "href": "https://i.letslynk.com/u/9fkoWokA/b/320.jpg" },
					"480": { "href": "https://i.letslynk.com/u/9fkoWokA/b/480.jpg" },
					"612": { "href": "https://i.letslynk.com/u/9fkoWokA/b/612.jpg" },
					"640": { "href": "https://i.letslynk.com/u/9fkoWokA/b/640.jpg" },
					"720": { "href": "https://i.letslynk.com/u/9fkoWokA/b/720.jpg" },
					"960": { "href": "https://i.letslynk.com/u/9fkoWokA/b/960.jpg" },
					"1080": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1080.jpg" },
					"1200": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1200.jpg" },
					"1600": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1600.jpg" }
				}
			},
            "team_name": "Kung Fu Masters", 
            "_deleted": false,
            "_modified": 1380621720
        }
    ],
    "_modified": 1380621720,
    "_links": {
        "self": { "href": "/users/1/goodies_sync?modified=1380621400&limit=10" },
        "next": { "href": "/users/1/goodies_sync?modified=1380621720&limit=10" }
    }
}
+++++
< 404
< Content-Type: application/json
{
    "error": "The requested resource could not be found"
}

--
User > TeamsSync
This method is for syncing teams to the mobile device.
--

Retrieve a list of teams

__Authentication:__ Required

__Authorization:__ The caller must be authorized as the owner of the user resource 

__URI Filters__: 

* modified (Integer) *the UTC unix time modified date*
* limit (Integer) *the maximum number of items to return*

    Example `/users/1/teams_sync?modified=1380621400&limit=10`
GET /users/{user_id}/teams_sync{?limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
{
    "teams": [
        {
            "_event_id": 1,
            "_team_id": 1,
            "name": "Letslynk Ltd",
            "user_level": "administrator",
            "_deleted": false,
            "_modified": 1380621600
        },
        {
            "_event_id": 2,
            "_team_id": 2,
            "name": "Bodswap",
            "user_level": "member",
            "_deleted": false,
            "_modified": 1380621720
        }
    ],
    "_modified": 1380621720,
    "_links": {
        "self": { "href": "/users/1/teams_sync?modified=1380621400&limit=10" },
        "next": { "href": "/users/1/teams_sync?modified=1380621720&limit=10" }
    }
}
+++++
< 404
< Content-Type: application/json
{
    "error": "The requested resource could not be found"
}


--
User > InvitesSync
This method is for syncing teams to the mobile device.
--

Retrieve a list of invites

__Authentication:__ Required

__Authorization:__ The caller must be authorized as the owner of the user resource 

__URI Filters__: 

* modified (Integer) *the UTC unix time modified date*
* limit (Integer) *the maximum number of items to return*

    Example `/users/1/invites_sync?modified=1380621400&limit=10`
GET /users/{user_id}/invites_sync{?limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
{
    "invites": [
        {
            "_invite_id": 1,
            "type": "team_join",
            "status": "pending",
            "level": "member",
            "team_name": "Kung Fu Masters",
            "team_id": 1,
            "event_name": "The Food Show 2013",
            "event_id": 1,
            "date": "2014-03-19T10:53:12Z",
            "_deleted": false,
            "_modified": 1380621600
        },
        {
            "_invite_id": 2,
            "type": "event_staff",
            "status": "pending",
            "level": "admin",
            "event_name": "The Food Show 2013",
            "event_id": 1,
            "date": "2014-03-19T10:53:12Z",
            "_deleted": false,
            "_modified": 1380621720
        },
        {
            "_invite_id": 3,
            "type": "event_visit",
            "status": "pending",
            "event_name": "The Food Show 2013",
            "event_id": 1,
            "date": "2014-03-19T10:53:12Z",
            "_deleted": false,
            "_modified": 1380621720
        },
        {
            "_invite_id": 4,
            "type": "team_create",
            "status": "pending",
            "team_name": "Kung Fu Masters",
            "event_name": "The Food Show 2013",
            "event_id": 1,
            "date": "2014-03-19T10:53:12Z",
            "_deleted": false,
            "_modified": 1380621720
        },
        
    ],
    "_modified": 1380621720,
    "_links": {
        "self": { "href": "/users/1/invites_sync?modified=1380621400&limit=10" },
        "next": { "href": "/users/1/invites_sync?modified=1380621720&limit=10" }
    }
}
+++++
< 404
< Content-Type: application/json
{
    "error": "The requested resource could not be found"
}


--
Team > ActivitySync

This method is for syncing activities to the mobile device.
--

Retrieve a collection of user activities

__Authentication:__ Required

__Authorization:__ The caller must be authorized as a member of the team resource

__URI Filters__: 

* modified (Integer) *the UTC unix time modified date*
* limit (Integer) *the maximum number of items to return*

     Example: `/teams/1/activity_sync?modified=1380621400&limit=10`
GET /teams/{team_id}/activity_sync{?limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
{
    "activities": [
        {
            "_activity_id": 1,
            "type": "connection",
            "date": 1380621600,
            "event_id": 1,
            "_modified": 1380621600
        },
        {
            "_activity_id": 2,
            "type": "goodie",
            "date": 1380610110,
            "event_id": 1,
            "_modified": 1380621720
        }
    ],
    "_modified": 1380621720,
    "_links": {
        "self": { "href": "/teams/1/activity_sync?modified=1380621400&limit=10" },
        "next": { "href": "/teams/1/activity_sync?modified=1380621720&limit=10" }
    }
}
+++++
< 404
< Content-Type: application/json
{
    "error": "The requested resource could not be found"
}


--
Team > ConnectionsSync
This method is for syncing connections to the mobile device.
--

Retrieve a list of connections

__Authentication:__ Required

__Authorization:__ The caller must be authorized as a member of the team resource 

__URI Filters__: 

* modified (Integer) *the UTC unix time modified date*
* limit (Integer) *the maximum number of items to return*

    Example `/teams/1/connections_sync?modified=1380621400&limit=10`
GET /teams/{team_id}/connections_sync{?limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
{
    "connections": [
        {
            "_connection_id": 1,
            "activity_id": 1,
            "contact_id": 10,
            "_modified": 1380621600
        },
        {
            "_connection_id": 2,
            "activity_id": 2,
            "contact_id": 11,
            "_modified": 1380621720
        }
    ],
    "_modified": 1380621720,
    "_links": {
        "self": { "href": "/teams/1/connections_sync?modified=1380621400&limit=10" },
        "next": { "href": "/teams/1/connections_sync?modified=1380621720&limit=10" }
    }
}
+++++
< 404
< Content-Type: application/json
{
    "error": "The requested resource could not be found"
}


--
Team > ContactsSync
This method is for syncing contacts to the mobile device
--

Retreive a list of contacts

__Authentication:__ Required

__Authorization:__ The caller must be authorized as the a member of the team resource 

__URI Filters__: 

* modified (Integer) *the UTC unix time modified date*
* limit (Integer) *the maximum number of items to return*

    Example `/teams/1/contacts_sync?modified=1380621400&limit=10`
GET /teams/{team_id}/contacts_sync{?limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
{
    "contacts": [
        {
            "_contact_id": 10,
            "email" : "stevensegal@kickass.com",
            "title" : "Mr",
            "first_name" : "Steven",
            "last_name" : "Segal",
            "home_telephone" : "04444 123 456",
            "mobile_telephone" : "05555 123 456",
            "work_telephone" : "06666 123 456",
            "linked_in" : "http://linked.in/steven_segal",
            "facebook" : "http://facebook.com/stevan_segal",
            "twitter" : "@steven_segal",
            "google" : "+steven_segal",
            "company" : "Kick Ass Ltd",
            "job_title" : "Ass Kicker",
            "address_line_1" : "Address 1",
            "address_line_2" : "Address 2",
            "address_line_3" : "Address 3",
            "address_line_4" : "Address 4",
            "locality" : "NY",
            "region" : "NY",
            "postcode" : "K1KA55",
            "country" : "USA",
            "_qr_code": "12434-12414-asdsa1-123123",
            "avatar": {
                "_links" : {
                    "original": { "href": "https://i.letslynk.com/u/9fkoWokA/a/orig.jpg" },
                    "38": { "href": "https://i.letslynk.com/u/9fkoWokA/a/38.jpg" },
                    "50": { "href": "https://i.letslynk.com/u/9fkoWokA/a/50.jpg" },
                    "75": { "href": "https://i.letslynk.com/u/9fkoWokA/a/75.jpg" },
                    "100": { "href": "https://i.letslynk.com/u/9fkoWokA/a/100.jpg" },
                    "150": { "href": "https://i.letslynk.com/u/9fkoWokA/a/150.jpg" },
                    "200": { "href": "https://i.letslynk.com/u/9fkoWokA/a/200.jpg" },
                    "300": { "href": "https://i.letslynk.com/u/9fkoWokA/a/300.jpg" }
                    }
            },
            "banner": {
                "_links" : {
                    "original": { "href": "https://i.letslynk.com/u/9fkoWokA/b/orig.jpg" },
                    "320": { "href": "https://i.letslynk.com/u/9fkoWokA/b/320.jpg" },
                    "480": { "href": "https://i.letslynk.com/u/9fkoWokA/b/480.jpg" },
                    "612": { "href": "https://i.letslynk.com/u/9fkoWokA/b/612.jpg" },
                    "640": { "href": "https://i.letslynk.com/u/9fkoWokA/b/640.jpg" },
                    "720": { "href": "https://i.letslynk.com/u/9fkoWokA/b/720.jpg" },
                    "960": { "href": "https://i.letslynk.com/u/9fkoWokA/b/960.jpg" },
                    "1080": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1080.jpg" },
                    "1200": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1200.jpg" },
                    "1600": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1600.jpg" }
                }
            },
            "_deleted": false,
            "_modified": 1380621600
        },
        {
            "_contact_id": 11,
            "email" : "brucelee@kickass.com",
            "title" : "Mr",
            "first_name" : "Bruce",
            "last_name" : "Lee",
            "home_telephone" : "04444 123 457",
            "mobile_telephone" : "05555 123 457",
            "work_telephone" : "06666 123 457",
            "linked_in" : "http://linked.in/bruce_lee",
            "facebook" : "http://facebook.com/bruce_lee",
            "twitter" : "@bruce_lee",
            "google" : "+bruce_lee",
            "company" : "Kick Ass Ltd",
            "job_title" : "Ass Kicker",
            "address_line_1" : "Address 1",
            "address_line_2" : "Address 2",
            "address_line_3" : "Address 3",
            "address_line_4" : "Address 4",
            "locality" : "NY",
            "region" : "NY",
            "postcode" : "K1KA55",
            "country" : "USA",
            "_qr_code": "12434-12414-asdsa1-123124",
            "avatar": {
                "_links" : {
                    "original": { "href": "https://i.letslynk.com/u/9fkoWokA/a/orig.jpg" },
                    "38": { "href": "https://i.letslynk.com/u/9fkoWokA/a/38.jpg" },
                    "50": { "href": "https://i.letslynk.com/u/9fkoWokA/a/50.jpg" },
                    "75": { "href": "https://i.letslynk.com/u/9fkoWokA/a/75.jpg" },
                    "100": { "href": "https://i.letslynk.com/u/9fkoWokA/a/100.jpg" },
                    "150": { "href": "https://i.letslynk.com/u/9fkoWokA/a/150.jpg" },
                    "200": { "href": "https://i.letslynk.com/u/9fkoWokA/a/200.jpg" },
                    "300": { "href": "https://i.letslynk.com/u/9fkoWokA/a/300.jpg" }
                    }
            },
            "banner": {
                "_links" : {
                    "original": { "href": "https://i.letslynk.com/u/9fkoWokA/b/orig.jpg" },
                    "320": { "href": "https://i.letslynk.com/u/9fkoWokA/b/320.jpg" },
                    "480": { "href": "https://i.letslynk.com/u/9fkoWokA/b/480.jpg" },
                    "612": { "href": "https://i.letslynk.com/u/9fkoWokA/b/612.jpg" },
                    "640": { "href": "https://i.letslynk.com/u/9fkoWokA/b/640.jpg" },
                    "720": { "href": "https://i.letslynk.com/u/9fkoWokA/b/720.jpg" },
                    "960": { "href": "https://i.letslynk.com/u/9fkoWokA/b/960.jpg" },
                    "1080": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1080.jpg" },
                    "1200": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1200.jpg" },
                    "1600": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1600.jpg" }
                }
            },
            "_deleted": false,
            "_modified": 1380621720
        }
    ],
    "_modified": 1380621720,
    "_links": {
        "self": { "href": "/teams/1/connections_sync?modified=1380621400&limit=10" },
        "next": { "href": "/teams/1/connections_sync?modified=1380621720&limit=10" }
    }
}


--
Team > TagsSync
This method is for syncing tags to the mobile device.
--

Retrieve a list of tags

__Authentication:__ Required

__Authorization:__ The caller must be authorized as a member of the team resource 

__URI Filters__: 

* modified (Integer) *the UTC unix time modified date*
* limit (Integer) *the maximum number of items to return*

    Example `/teams/1/tags_sync?modified=1380621400&limit=10`
GET /teams/{team_id}/tags_sync{?limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
{
    "tags": [
        {
            "_tag_id": 1,
            "name": "Hot Lead",
            "colour": "F7686B",
            "icon": "flame",
            "_deleted": false,
            "_modified": 1380621600
        },
        {
            "_tag_id": 2,
            "name": "Call back",
            "colour": "47B569",
            "icon": "phone",
            "_deleted": false,
            "_modified": 1380621720
        }
    ],
    "_modified": 1380621720,
    "_links": {
        "self": { "href": "/teams/1/tags_sync?modified=1380621400&limit=10" },
        "next": { "href": "/teams/1/tags_sync?modified=1380621720&limit=10" }
    }
}
+++++
< 404
< Content-Type: application/json
{
    "error": "The requested resource could not be found"
}


--
Team > TagsAssignmentsSync
This method is for syncing tag assignments to the mobile device.
--

Retrieve a list of tag assignments

__Authentication:__ Required

__Authorization:__ The caller must be authorized as a member of the team resource 

__URI Filters__: 

* modified (Integer) *the UTC unix time modified date*
* limit (Integer) *the maximum number of items to return*

    Example `/teams/1/tags_sync?modified=1380621400&limit=10`
GET /teams/{team_id}/tag_assignments_sync{?limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
{
    "tags_assignments": [
        {
            "_tag_assignment_id": 1,
            "tag_id": 1,
            "contact_id": 10,
            "_deleted": false,
            "_modified": 1380621600
        },
        {
            "_tag_assignment_id": 2,
            "tag_id": 2,
            "contact_id": 10,
            "_deleted": false,
            "_modified": 1380621720
        }
    ],
    "_modified": 1380621720,
    "_links": {
        "self": { "href": "/teams/1/tag_assignments_sync?modified=1380621400&limit=10" },
        "next": { "href": "/teams/1/tag_assignments_sync?modified=1380621720&limit=10" }
    }
}
+++++
< 404
< Content-Type: application/json
{
    "error": "The requested resource could not be found"
}


--
Team > NotesSync
This method is for syncing notes to the mobile device.
--

Retrieve a list of notes

__Authentication:__ Required

__Authorization:__ The caller must be authorized as the owner of the user resource 

__URI Filters__: 

* modified (Integer) *the UTC unix time modified date*
* limit (Integer) *the maximum number of items to return*

    Example `/teams/1/tags_sync?modified=1380621400&limit=10`
GET /teams/{team_id}/notes_sync{?limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
{
    "notes": [
        {
            "_note_id": 1,
            "contact_id": 10,
            "note": "This is the note text. Blah blah",
            "date": 1380621600, 
            "_deleted": false,
            "_modified": 1380621600
        },
        {
            "_note_id": 2,
            "contact_id": 10,
            "note": "This is another note. Blah blah",
            "date": 1380621700, 
            "_deleted": false,
            "_modified": 1380621720
        }
    ],
    "_modified": 1380621720,
    "_links": {
        "self": { "href": "/teams/1/notes_sync?modified=1380621400&limit=10" },
        "next": { "href": "/teams/1/notes_sync?modified=1380621720&limit=10" }
    }
}
+++++
< 404
< Content-Type: application/json
{
    "error": "The requested resource could not be found"
}


--
Team > GoodiesSync
This method is for syncing goodies to the mobile device.
--

Retrieve a list of notes

__Authentication:__ Required

__Authorization:__ The caller must be authorized as a member of the team resource 

__URI Filters__: 

* modified (Integer) *the UTC unix time modified date*
* limit (Integer) *the maximum number of items to return*

    Example `/teams/1/goodies_sync?modified=1380621400&limit=10`
GET /teams/{team_id}/goodies_sync{?limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
{
    "goodies": [
        {
            "_goodie_id": 1,
            "activity_id": 9,
            "collected_date": 1380621600,
            "name": "2013 Product Brochure",
            "type": "Document",
            "sub_type": "pdf",
            "url": "/docs/team/1/asdpoqwefpj.pdf",
            "team_name": "Kung Fu Masters",
            "_deleted": false,
            "_modified": 1380621600
        },
        {
            "_goodie_id": 2,
            "activity_id": 10,
            "collected_date": 1380621712,
            "name": "2013 Fact File",
            "type": "video",
            "url": "/docs/team/1/asasfafgwwec.pdf",
            "thumbnail": {
				"_links": {
					"original": { "href": "https://i.letslynk.com/u/9fkoWokA/b/orig.jpg" },
					"320": { "href": "https://i.letslynk.com/u/9fkoWokA/b/320.jpg" },
					"480": { "href": "https://i.letslynk.com/u/9fkoWokA/b/480.jpg" },
					"612": { "href": "https://i.letslynk.com/u/9fkoWokA/b/612.jpg" },
					"640": { "href": "https://i.letslynk.com/u/9fkoWokA/b/640.jpg" },
					"720": { "href": "https://i.letslynk.com/u/9fkoWokA/b/720.jpg" },
					"960": { "href": "https://i.letslynk.com/u/9fkoWokA/b/960.jpg" },
					"1080": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1080.jpg" },
					"1200": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1200.jpg" },
					"1600": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1600.jpg" }
				}
			},
            "team_name": "Kung Fu Masters", 
            "_deleted": false,
            "_modified": 1380621712
        },
        {
            "_goodie_id": 3,
            "activity_id": 11,
            "collected_date": 1380621720,
            "name": "2013 Picture",
            "type": "image",
            "url": "https://www.youtube.com/watch?v=XJDUgkSzh-Y",
            "thumbnail": {
				"_links": {
					"original": { "href": "https://i.letslynk.com/u/9fkoWokA/b/orig.jpg" },
					"320": { "href": "https://i.letslynk.com/u/9fkoWokA/b/320.jpg" },
					"480": { "href": "https://i.letslynk.com/u/9fkoWokA/b/480.jpg" },
					"612": { "href": "https://i.letslynk.com/u/9fkoWokA/b/612.jpg" },
					"640": { "href": "https://i.letslynk.com/u/9fkoWokA/b/640.jpg" },
					"720": { "href": "https://i.letslynk.com/u/9fkoWokA/b/720.jpg" },
					"960": { "href": "https://i.letslynk.com/u/9fkoWokA/b/960.jpg" },
					"1080": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1080.jpg" },
					"1200": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1200.jpg" },
					"1600": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1600.jpg" }
				}
			},
            "team_name": "Kung Fu Masters", 
            "_deleted": false,
            "_modified": 1380621720
        }
    ],
    "_modified": 1380621720,
    "_links": {
        "self": { "href": "/teams/1/goodies_sync?modified=1380621400&limit=10" },
        "next": { "href": "/teams/1/goodies_sync?modified=1380621720&limit=10" }
    }
}
+++++
< 404
< Content-Type: application/json
{
    "error": "The requested resource could not be found"
}


--
Event > RegistrantsSync
This method is for syncing event registrants to the mobile device
--

Retreive a list of event registrants

__Authentication:__ Required

__Authorization:__ The caller must be authorized as a scanner of the event resource 

__URI Filters__: 

* modified (Integer) *the UTC unix time modified date*
* limit (Integer) *the maximum number of items to return*

    Example `/events/1/registrants_sync?modified=1380621400&limit=10`
GET /events/{event_id}/registrants_sync{?limit,modified}
> Content-Type: application/json
> Authorization: Basic {your encoded token}
< 200
{
    "_modified": 1392112171,
    "_links": {
        "self": {
            "href": "http://178.79.170.67:8000/events/1/registrants_sync"
        }
    },
    "registrations": [
        {
            "_modified": 1392112169,
            "_deleted": false
            "registration_date": "2014-02-11T09:49:29Z",
            "user": {
                "_user_id": 1,
                "title": "Mr",
                "first_name": "Tito",
                "last_name": "Ortiz",
                "email": "tito.ortiz@mma.com"
                "home_telephone": "04444 123 456",
                "mobile_telephone": "05555 123 456",
                "work_telephone": "06666 123 456",
                "linked_in": "http://linked.in/tito_ortiz",
                "facebook": "http://facebook.com/tito_ortiz",
                "twitter": "@tito_ortiz",
                "google": "+tito_ortiz",
                "company": "Kick Ass Ltd",
                "job_title": "Ass Kicker",
                "address_line_1": "Address 1",
                "address_line_2": "Address 2",
                "address_line_3": "Address 3",
                "address_line_4": "Address 4",
                "locality": "NY",
                "region": "NY",
                "postcode": "K1KA55",
                "country": "USA",
                "_qr_url": "https://qr.letslynk.com/u/oO68mZwLTvi7bWu5vTgKEQ/Tito%20Ortiz",
                "_qr_code": "d6603fb5-a2d3-4e1a-9df3-bd43aa89faf1",
                "avatar": {
                    "_links": {
                        "38": { "href": "https://i.letslynk.com/u/9fkoWokA/a/38.jpg" },
                        "50": { "href": "https://i.letslynk.com/u/9fkoWokA/a/50.jpg" },
                        "75": { "href": "https://i.letslynk.com/u/9fkoWokA/a/75.jpg" },
                        "100": { "href": "https://i.letslynk.com/u/9fkoWokA/a/100.jpg" },
                        "150": { "href": "https://i.letslynk.com/u/9fkoWokA/a/150.jpg" },
                        "200": { "href": "https://i.letslynk.com/u/9fkoWokA/a/200.jpg" },
                        "300": { "href": "https://i.letslynk.com/u/9fkoWokA/a/300.jpg" }
                    }
                },
                "banner": {
                    "_links": {
                        "320": { "href": "https://i.letslynk.com/u/9fkoWokA/b/320.jpg" },
                        "480": { "href": "https://i.letslynk.com/u/9fkoWokA/b/480.jpg" },
                        "612": { "href": "https://i.letslynk.com/u/9fkoWokA/b/612.jpg" },
                        "640": { "href": "https://i.letslynk.com/u/9fkoWokA/b/640.jpg" },
                        "720": { "href": "https://i.letslynk.com/u/9fkoWokA/b/720.jpg" },
                        "960": { "href": "https://i.letslynk.com/u/9fkoWokA/b/960.jpg" },
                        "1080": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1080.jpg" },
                        "1200": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1200.jpg" },
                        "1600": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1600.jpg" }
                    }
                }
            }
        },
        {
            "_modified": 1392112171,
            "_deleted": false,
            "registration_date": "2014-02-11T09:49:31Z",
            "user": {
                "_user_id": 2
                "title": "Mr",
                "first_name": "Bas",
                "last_name": "Rutten",
                "email": "bas.rutten@mma.com"
                "home_telephone": "04444 123 456",
                "mobile_telephone": "05555 123 456",
                "work_telephone": "06666 123 456",
                "linked_in": "http://linked.in/bas_rutten",
                "facebook": "http://facebook.com/bas_rutten",
                "twitter": "@bas_rutten",
                "google": "+bas_rutten",
                "company": "Kick Ass Ltd",
                "job_title": "Ass Kicker",
                "address_line_1": "Address 1",
                "address_line_2": "Address 2",
                "address_line_3": "Address 3",
                "address_line_4": "Address 4",
                "locality": "NY",
                "region": "NY",
                "postcode": "K1KA55",
                "country": "USA",
                "_qr_url": "https://qr.letslynk.com/u/oO68mZwLTvi7bWu5vTgKEQ/Bas%20Rutten",
                "_qr_code": "20f0b83c-16e5-49ac-a0fa-2883f7219091",
                "avatar": {
                    "_links": {
                        "38": { "href": "https://i.letslynk.com/u/9fkoWokA/a/38.jpg" },
                        "50": { "href": "https://i.letslynk.com/u/9fkoWokA/a/50.jpg" },
                        "75": { "href": "https://i.letslynk.com/u/9fkoWokA/a/75.jpg" },
                        "100": { "href": "https://i.letslynk.com/u/9fkoWokA/a/100.jpg" },
                        "150": { "href": "https://i.letslynk.com/u/9fkoWokA/a/150.jpg" },
                        "200": { "href": "https://i.letslynk.com/u/9fkoWokA/a/200.jpg" },
                        "300": { "href": "https://i.letslynk.com/u/9fkoWokA/a/300.jpg" }
                    }
                },
                "banner": {
                    "_links": {
                        "320": { "href": "https://i.letslynk.com/u/9fkoWokA/b/320.jpg" },
                        "480": { "href": "https://i.letslynk.com/u/9fkoWokA/b/480.jpg" },
                        "612": { "href": "https://i.letslynk.com/u/9fkoWokA/b/612.jpg" },
                        "640": { "href": "https://i.letslynk.com/u/9fkoWokA/b/640.jpg" },
                        "720": { "href": "https://i.letslynk.com/u/9fkoWokA/b/720.jpg" },
                        "960": { "href": "https://i.letslynk.com/u/9fkoWokA/b/960.jpg" },
                        "1080": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1080.jpg" },
                        "1200": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1200.jpg" },
                        "1600": { "href": "https://i.letslynk.com/u/9fkoWokA/b/1600.jpg" }
                    }
                }
            }
        }
    ]
}

